### ISSUE TITLE
Photo posts render with different <p> padding to regular posts

### ISSUE THREAD

**Issue by keithamoss** [govhackaustralia/project-jabberwocky#1]
<img width="404" alt="screen shot 2016-03-24 at 20 28 30" src="https://cloud.githubusercontent.com/assets/1672960/14017014/06925372-f1ff-11e5-96a1-26c37cb3b67f.png">

<img width="323" alt="screen shot 2016-03-24 at 20 27 40" src="https://cloud.githubusercontent.com/assets/1672960/14017015/0695949c-f1ff-11e5-9b72-0635108331e2.png">

<img width="323" alt="screen shot 2016-03-24 at 20 27 29" src="https://cloud.githubusercontent.com/assets/1672960/14017016/0699deb2-f1ff-11e5-93f3-3385e4084177.png">

**Comment by keithamoss** [comment]
Commented this out in `screen.css`

```css
div.content.photo-post p, div.content.photo-post iframe {
  padding: 40px 0 0 0;
  margin:0;
}
```
